import { FolderOpened, Grid, PictureFilled, SwitchButton, Tickets } from "@element-plus/icons-vue";

export default [
  {
    title: "示例容器",
    items: [
      {
        icon: FolderOpened,
        text: "组",
        type: "container",
      },
      {
        icon: FolderOpened,
        text: "蒙层",
        type: "overlay",
      },
    ],
  },
  {
    title: "示例组件",
    items: [
      {
        icon: Tickets,
        text: "文本",
        type: "text",
      },
      // {
      //   icon: SwitchButton,
      //   text: '按钮',
      //   type: 'button',
      // },
      {
        icon: PictureFilled,
        text: "图片",
        type: "img",
      },
      // {
      //   icon: Grid,
      //   text: '二维码',
      //   type: 'qrcode',
      // },
      // {
      //   icon: Grid,
      //   text: '步骤',
      //   type: 'steps',
      // },
      // {
      //   icon: Tickets,
      //   text: '测试组件',
      //   type: 'test',
      // },
    ],
  },
  {
    title: "组合",
    items: [
      {
        icon: Tickets,
        text: "弹窗",
        data: {
          type: "overlay",
          atr: {
            "v-show": false,
          },
          HyperText: "div",
          style: {
            position: "fixed",
            width: "100%",
            height: "100%",
            top: 0,
            left: 0,
            backgroundColor: "rgba(0, 0, 0, 0.8)",
          },
          name: "弹窗",
          items: [
            {
              type: "container",
              style: {
                position: "absolute",
                width: "80%",
                height: "400",
                top: "143.87",
                left: 37.5,
                backgroundColor: "rgba(255, 255, 255, 1)",
                backgroundRepeat: "no-repeat",
                backgroundSize: "100% 100%",
              },
              name: "组",
              items: [],
              layout: "absolute",
            },
          ],
        },
      },
      {
        icon: Tickets,
        text: "标签页",
        data: {
          type: "tabs",
          style: {
            position: "absolute",
            width: "1024",
            height: "500",
            top: 257,
            left: 101,
            textAlign: "",
            right: "",
            bottom: "",
            borderWidth: "0",
            borderColor: "",
            borderRadius: "0",
            borderStyle: "none",
            backgroundImage: "",
            backgroundColor: "",
            backgroundRepeat: "no-repeat",
            backgroundSize: "100% 100%",
            color: "",
            fontSize: "",
            fontWeight: "",
            transform: {
              rotate: "",
              scale: "",
            },
          },
          name: "tabs",
          HyperText: "el-tabs",
          atr: {
            type: "",
            "tab-position": "top",
            "v-model": "1",
          },
          layout: "relative",
          items: [
            {
              type: "tabpane",
              style: {
                position: "relative",
                width: "300",
                height: "500",
                top: 0,
                left: 0,
                textAlign: "",
                right: "",
                bottom: "",
                borderWidth: "0",
                borderColor: "",
                borderRadius: "0",
                borderStyle: "none",
                backgroundImage: "",
                backgroundColor: "",
                backgroundRepeat: "no-repeat",
                backgroundSize: "100% 100%",
                color: "",
                fontSize: "",
                fontWeight: "",
                transform: {
                  rotate: "",
                  scale: "",
                },
              },
              name: "tabpane",
              HyperText: "el-tab-pane",
              atr: {
                label: "标签页1",
              },
              items: [
                {
                  type: "container",
                  layout: "absolute",
                  style: {
                    width: 1028,
                    height: 436,
                    position: "absolute",
                    top: -8,
                    left: -17,
                  },
                  name: "组",
                  items: [],
                },
              ],
              events: "",
              created: "",
              mounted: "",
            },
            {
              type: "tabpane",
              style: {
                position: "relative",
                width: "300",
                height: "500",
                top: 0,
                left: 0,
                textAlign: "",
                right: "",
                bottom: "",
                borderWidth: "0",
                borderColor: "",
                borderRadius: "0",
                borderStyle: "none",
                backgroundImage: "",
                backgroundColor: "",
                backgroundRepeat: "no-repeat",
                backgroundSize: "100% 100%",
                color: "",
                fontSize: "",
                fontWeight: "",
                transform: {
                  rotate: "",
                  scale: "",
                },
              },
              name: "tabpane",
              HyperText: "el-tab-pane",
              atr: {
                label: "标签页2",
              },
              items: [
                {
                  type: "container",
                  layout: "absolute",
                  style: {
                    width: 1028,
                    height: 436,
                    position: "absolute",
                    top: -8,
                    left: -17,
                  },
                  name: "组",
                  items: [],
                },
              ],
              events: "",
              created: "",
              mounted: "",
            },
          ],
          events: "",
          created: "",
          mounted: "",
        },
      },
      {
        icon: Tickets,
        text: "菜单栏",
        data: {
          type: "menu",
          style: {
            position: "absolute",
            width: 182,
            height: 1017,
            top: 3,
            left: 6,
            textAlign: "",
            right: "",
            bottom: "",
            borderWidth: "0",
            borderColor: null,
            borderRadius: "0",
            borderStyle: "none",
            backgroundImage: "",
            backgroundColor: null,
            backgroundRepeat: "no-repeat",
            backgroundSize: "100% 100%",
            color: "",
            fontSize: "",
            fontWeight: "",
            transform: {
              rotate: "",
              scale: "",
            },
          },
          name: "menu",
          atr: {
            ":default-active": 0,
            mode: "vertical",
            collapse: true,
          },
          layout: "relative",
          HyperText: "el-menu",
          items: [
            {
              type: "menuitem",
              style: {
                position: "relative",
                width: "100%",
                height: "auto",
                top: 0,
                left: 0,
                textAlign: "",
                right: "",
                bottom: "",
                borderWidth: "0",
                borderColor: "",
                borderRadius: "0",
                borderStyle: "none",
                backgroundImage: "",
                backgroundColor: null,
                backgroundRepeat: "no-repeat",
                backgroundSize: "100% 100%",
                color: "",
                fontSize: "",
                fontWeight: "",
                transform: {
                  rotate: "",
                  scale: "",
                },
              },
              name: "menuitem",
              atr: {
                ":default-active": 0,
                index: "0",
              },
              HyperText: "el-menu-item",
              items: [],
              text: "菜单栏一",
              events: "",
              created: "",
              mounted: "",
            },
            {
              type: "menuitem",
              style: {
                position: "relative",
                width: "100%",
                height: "auto",
                top: 0,
                left: 0,
                textAlign: "",
                right: "",
                bottom: "",
                borderWidth: "0",
                borderColor: "",
                borderRadius: "0",
                borderStyle: "none",
                backgroundImage: "",
                backgroundColor: "",
                backgroundRepeat: "no-repeat",
                backgroundSize: "100% 100%",
                color: "",
                fontSize: "",
                fontWeight: "",
                transform: {
                  rotate: "",
                  scale: "",
                },
              },
              name: "menuitem",
              atr: {
                ":default-active": 0,
                index: "1",
              },
              HyperText: "el-menu-item",
              items: [],
              text: "菜单栏二",
              events: "",
              created: "",
              mounted: "",
            },
            {
              type: "menuitem",
              style: {
                position: "relative",
                width: "100%",
                height: 56,
                top: 0,
                left: "0",
                textAlign: "",
                right: "",
                bottom: "",
                borderWidth: "0",
                borderColor: "",
                borderRadius: "0",
                borderStyle: "none",
                backgroundImage: "",
                backgroundColor: "",
                backgroundRepeat: "no-repeat",
                backgroundSize: "100% 100%",
                color: "",
                fontSize: "",
                fontWeight: "",
                transform: {
                  rotate: "",
                  scale: "",
                },
              },
              name: "menuitem",
              atr: {
                ":default-active": 0,
                index: "2",
              },
              HyperText: "el-menu-item",
              items: [],
              text: "菜单栏三",
              events: "",
              created: "",
              mounted: "",
            },
          ],
          events: "",
          created: "",
          mounted: "",
        },
      },
      {
        icon: Tickets,
        text: "选择框",
        data: {
          type: "elselect",
          style: {
            position: "absolute",
            width: "300px",
            height: "auto",
            top: 612.2807893705634,
            left: 227.95974995309422,
            textAlign: "",
            right: "",
            bottom: "",
            borderWidth: "0",
            borderColor: "",
            borderRadius: "0",
            borderStyle: "none",
            backgroundImage: "",
            backgroundColor: "",
            backgroundRepeat: "no-repeat",
            backgroundSize: "100% 100%",
            color: "",
            fontSize: "",
            fontWeight: "",
            transform: {
              rotate: "",
              scale: "",
            },
          },
          name: "elselect",
          atr: {
            placeholder: "请选择",
          },
          HyperText: "el-select",
          layout: "relative",
          items: [
            {
              type: "eloption",
              style: {
                position: "relative",
                width: "100%",
                height: "auto",
                top: 0,
                left: 0,
                textAlign: "",
                right: "",
                bottom: "",
                borderWidth: "0",
                borderColor: "",
                borderRadius: "0",
                borderStyle: "none",
                backgroundImage: "",
                backgroundColor: "",
                backgroundRepeat: "no-repeat",
                backgroundSize: "100% 100%",
                color: "",
                fontSize: "",
                fontWeight: "",
                transform: {
                  rotate: "",
                  scale: "",
                },
              },
              name: "eloption",
              atr: {
                placeholder: "请选择",
                label: "选项一",
                value: "1",
              },
              HyperText: "el-option",
              items: [],
              events: "",
              created: "",
              mounted: "",
            },
            {
              type: "eloption",
              style: {
                position: "relative",
                width: "100%",
                height: "auto",
                top: 0,
                left: 0,
                textAlign: "",
                right: "",
                bottom: "",
                borderWidth: "0",
                borderColor: "",
                borderRadius: "0",
                borderStyle: "none",
                backgroundImage: "",
                backgroundColor: "",
                backgroundRepeat: "no-repeat",
                backgroundSize: "100% 100%",
                color: "",
                fontSize: "",
                fontWeight: "",
                transform: {
                  rotate: "",
                  scale: "",
                },
              },
              name: "eloption",
              atr: {
                placeholder: "请选择",
                label: "选项二",
                value: "2",
              },
              HyperText: "el-option",
              items: [],
              events: "",
              created: "",
              mounted: "",
            },
          ],
          events: "",
          created: "",
          mounted: "",
        },
      },
    ],
  },
  {
    title: "基础组件",
    items: [
      {
        icon: Tickets,
        text: "ul",
        type: "ul",
      },
      {
        icon: Tickets,
        text: "ol",
        type: "ol",
      },
      {
        icon: Tickets,
        text: "li",
        type: "li",
      },
      {
        icon: Tickets,
        text: "input",
        type: "input",
      },
      {
        icon: Tickets,
        text: "button",
        type: "button",
      },
      {
        icon: Tickets,
        text: "table",
        type: "table",
      },
      {
        icon: Tickets,
        text: "thead",
        type: "thead",
      },
      {
        icon: Tickets,
        text: "tbody",
        type: "tbody",
      },
      {
        icon: Tickets,
        text: "th",
        type: "th",
      },
      {
        icon: Tickets,
        text: "tr",
        type: "tr",
      },
      {
        icon: Tickets,
        text: "td",
        type: "td",
      },
    ],
  },
  {
    title: "element组件",
    items: [
      {
        icon: Tickets,
        text: "link",
        type: "link",
      },
      {
        icon: Tickets,
        text: "badge",
        type: "badge",
      },
      {
        icon: Tickets,
        text: "card",
        type: "card",
      },
      {
        icon: Tickets,
        text: "tabs",
        type: "tabs",
      },
      {
        icon: Tickets,
        text: "tabpane",
        type: "tabpane",
      },
      {
        icon: Tickets,
        text: "menu",
        type: "menu",
      },
      {
        icon: Tickets,
        text: "menuitem",
        type: "menuitem",
      },
      {
        icon: Tickets,
        text: "datepicker",
        type: "datepicker",
      },
      {
        icon: Tickets,
        text: "elselect",
        type: "elselect",
      },
      {
        icon: Tickets,
        text: "eloption",
        type: "eloption",
      },
      {
        icon: Tickets,
        text: "elpaging",
        type: "elpaging"
      }
    ],
  },
  {
    title: "自定义组件",
    items: [
      {
        icon: Tickets,
        text: "底部按钮",
        type: "bottombutton",
      },
      {
        icon: Tickets,
        text: "定时器",
        type: "pagetimer",
      },
      // {
      //   icon: Tickets,
      //   text: 'sound',
      //   type: 'sound11',
      // },
      {
        icon: Tickets,
        text: "导航栏",
        type: "navigation",
      },
      {
        icon: Tickets,
        text: "容器",
        type: "framecontent",
      },
      {
        icon: Tickets,
        text: "呼叫",
        type: "callmanager",
      },
      {
        icon: Tickets,
        text: "返回主页",
        type: "backhome",
      },
      {
        icon: Tickets,
        text: "图片背景",
        type: "bgcontent",
      },
      {
        icon: Tickets,
        text: "轮播图",
        type: "carousel",
      },
      {
        icon: Tickets,
        text: "进度条",
        type: "progress",
      },
      {
        icon: Tickets,
        text: "选中框",
        type: "select_div",
      },
      {
        icon: Tickets,
        text: "循环flex容器",
        type: "flexfor",
      },
      {
        icon: Tickets,
        text: "scroll",
        type: "scroll",
      },
      {
        icon: Tickets,
        text: "ballontooltip",
        type: "ballontooltip",
      },
      {
        icon: Tickets,
        text: "clientconfirm",
        type: "clientconfirm",
      },
      {
        icon: Tickets,
        text: "zjdialog",
        type: "zjdialog",
      },
      {
        icon: Tickets,
        text: "percentbutton",
        type: "percentbutton",
      },
      {
        icon: Tickets,
        text: "输入框",
        type: "paperinput"
      },
      {
        icon: Tickets,
        text: "popUp",
        type: "popup"
      }
    ],
  },
];
