/*
 * Tencent is pleased to support the open source community by making TMagicEditor available.
 *
 * Copyright (C) 2023 THL A29 Limited, a Tencent company.  All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export default {
  id: "75f0extui9d7yksklx27hff8xg",
  name: "test",
  type: "app",
  codeBlocks: {
    code_5336: {
      name: "getData",
      params: [
        {
          name: "age",
        },
        {
          name: "studentName",
        },
      ],
    },
    code_5316: {
      name: "getList",
      params: [],
    },
  },
  items: [
    {
      type: "page",
      id: "page_299",
      name: "提示页面",
      title: "",
      layout: "absolute",
      style: {
        position: "relative",
        left: 0,
        top: 0,
        right: "",
        bottom: "",
        width: "1280",
        height: "1024",
        backgroundImage: "https://127.0.0.1:9000/img/back_1600x1200.bac1a12c.jpg",
        backgroundColor: null,
        backgroundRepeat: "no-repeat",
        backgroundSize: "100% 100%",
        color: "",
        fontSize: "",
        fontWeight: "",
        transform: {
          rotate: "",
          scale: "",
        },
      },
      events: [],
      created: {
        hookType: "code",
        hookData: [
          {
            codeId: "code_5336",
            params: {
              studentName: "lisa",
              age: 14,
            },
          },
          {
            codeId: "code_5316",
            params: {},
          },
        ],
      },
      items: [
        {
          id: "framecontent_a44aa26a",
          type: "framecontent",
          style: {
            position: "absolute",
            width: "1250",
            height: "880",
            top: "90",
            left: 15,
            right: "",
            bottom: "",
            backgroundImage: "",
            backgroundColor: "",
            backgroundRepeat: "no-repeat",
            backgroundSize: "100% 100%",
            color: "",
            fontSize: "",
            fontWeight: "",
            transform: {
              rotate: "",
              scale: "",
            },
          },
          name: "容器",
          _appname: "应用名",
          _title: "标题",
          _icon: "card",
          HyperText: "frame-content",
          items: [
            {
              id: "bgcontent_7caf8434",
              type: "bgcontent",
              style: {
                position: "absolute",
                width: "1000",
                height: "585",
                top: "180",
                left: 125,
                right: "",
                bottom: "",
                backgroundImage: "",
                backgroundColor: "",
                backgroundRepeat: "no-repeat",
                backgroundSize: "100% 100%",
                color: "",
                fontSize: "",
                fontWeight: "",
                transform: {
                  rotate: "",
                  scale: "",
                },
              },
              name: "图片背景",
              appName: "MainFramePage",
              pageName: "SafeNote",
              imgName: "bg.png",
              HyperText: "bg-content",
              events: [],
              created: "",
              mounted: "",
            },
            {
              id: "container_f6b08745",
              type: "container",
              layout: "absolute",
              style: {
                width: "800",
                height: "500",
                position: "absolute",
                top: "220",
                left: 225,
                right: "",
                bottom: "",
                backgroundImage: "",
                backgroundColor: "",
                backgroundRepeat: "no-repeat",
                backgroundSize: "100% 100%",
                color: "",
                fontSize: "",
                fontWeight: "",
                transform: {
                  rotate: "",
                  scale: "",
                },
              },
              name: "组",
              items: [
                {
                  id: "text_74b91e62",
                  type: "text",
                  style: {
                    width: "auto",
                    height: "auto",
                    position: "absolute",
                    top: "20",
                    left: 344,
                    right: "",
                    bottom: "",
                    backgroundImage: "",
                    backgroundColor: "",
                    backgroundRepeat: "no-repeat",
                    backgroundSize: "100% 100%",
                    color: "rgba(230, 61, 61, 1)",
                    fontSize: "28",
                    fontWeight: "700",
                    transform: {
                      rotate: "",
                      scale: "",
                    },
                  },
                  name: "文本",
                  text: "温馨提示",
                  multiple: true,
                  events: [],
                  created: "",
                  mounted: "",
                },
                {
                  id: "text_edb7ed0d",
                  type: "text",
                  style: {
                    width: "700",
                    height: "auto",
                    position: "absolute",
                    top: "80",
                    left: 50,
                    right: "",
                    bottom: "",
                    backgroundImage: "",
                    backgroundColor: "",
                    backgroundRepeat: "no-repeat",
                    backgroundSize: "100% 100%",
                    color: "",
                    fontSize: "19",
                    fontWeight: "",
                    transform: {
                      rotate: "",
                      scale: "",
                    },
                  },
                  name: "文本",
                  text: " 1、办理业务前，请留意查看自助设备插卡口键盘及机器其他部位是否加装或粘贴异物，注意周围是否有可疑人员。 ",
                  multiple: true,
                  events: [],
                  created: "",
                  mounted: "",
                },
                {
                  id: "text_872dce92",
                  type: "text",
                  style: {
                    width: "700",
                    height: "auto",
                    position: "absolute",
                    top: "160",
                    left: "50",
                    right: "",
                    bottom: "",
                    backgroundImage: "",
                    backgroundColor: "",
                    backgroundRepeat: "no-repeat",
                    backgroundSize: "100% 100%",
                    color: "",
                    fontSize: "19",
                    fontWeight: "",
                    transform: {
                      rotate: "",
                      scale: "",
                    },
                  },
                  name: "文本",
                  text: " 2、切勿相信手机信息中的银行卡交易或中奖信息，切勿拨打粘贴在自助设备上除95392外的任何联系电话，警惕不法分子窥视，请不要向他人透露您的密码。 ",
                  multiple: true,
                  events: [],
                  created: "",
                  mounted: "",
                },
                {
                  id: "text_5aa4dcad",
                  type: "text",
                  style: {
                    width: "700",
                    height: "auto",
                    position: "absolute",
                    top: "240",
                    left: "50",
                    right: "",
                    bottom: "",
                    backgroundImage: "",
                    backgroundColor: "",
                    backgroundRepeat: "no-repeat",
                    backgroundSize: "100% 100%",
                    color: "",
                    fontSize: "19",
                    fontWeight: "",
                    transform: {
                      rotate: "",
                      scale: "",
                    },
                  },
                  name: "文本",
                  text: " 3、输入密码应快速并尽量用手遮挡，以防不法分子窥视，请不要向他人透露您的密码。 ",
                  multiple: true,
                  events: [],
                  created: "",
                  mounted: "",
                },
                {
                  id: "text_b240f5e3",
                  type: "text",
                  style: {
                    width: "700",
                    height: "auto",
                    position: "absolute",
                    top: "320",
                    left: 50,
                    right: "",
                    bottom: "",
                    backgroundImage: "",
                    backgroundColor: "",
                    backgroundRepeat: "no-repeat",
                    backgroundSize: "100% 100%",
                    color: "",
                    fontSize: "19",
                    fontWeight: "",
                    transform: {
                      rotate: "",
                      scale: "",
                    },
                  },
                  name: "文本",
                  text: " 4、在交易过程中请不要离开自助设备，尽量避免被他人吸引注意力，交易完成后，应及时退出系统并取回银行卡。 ",
                  multiple: true,
                  events: [],
                  created: "",
                  mounted: "",
                },
                {
                  id: "text_591bd7ef",
                  type: "text",
                  style: {
                    width: "700",
                    height: "auto",
                    position: "absolute",
                    top: "400",
                    left: "50",
                    right: "",
                    bottom: "",
                    backgroundImage: "",
                    backgroundColor: "",
                    backgroundRepeat: "no-repeat",
                    backgroundSize: "100% 100%",
                    color: "",
                    fontSize: "19",
                    fontWeight: "",
                    transform: {
                      rotate: "",
                      scale: "",
                    },
                  },
                  name: "文本",
                  text: " 5、办理业务时，如果设备吞卡，请尽快联系营业机构人员或拨打95392的客户服务电话。 ",
                  multiple: true,
                  events: [],
                  created: "",
                  mounted: "",
                },
                {
                  id: "container_28284853",
                  type: "container",
                  layout: "absolute",
                  style: {
                    width: 1228,
                    height: "100",
                    position: "absolute",
                    top: "550",
                    left: -214,
                    right: "",
                    bottom: "",
                    backgroundImage: "",
                    backgroundColor: "",
                    backgroundRepeat: "no-repeat",
                    backgroundSize: "100% 100%",
                    color: "rgba(255, 0, 0, 0)",
                    fontSize: "",
                    fontWeight: "",
                    transform: {
                      rotate: "",
                      scale: "",
                    },
                  },
                  name: "组",
                  items: [
                    {
                      id: "backhome_0d0a887b",
                      type: "backhome",
                      style: {
                        position: "absolute",
                        width: "200",
                        height: "60",
                        top: "20",
                        left: "50",
                        right: "",
                        bottom: "",
                        backgroundImage: "",
                        backgroundColor: "",
                        backgroundRepeat: "no-repeat",
                        backgroundSize: "100% 100%",
                        color: "",
                        fontSize: "",
                        fontWeight: "",
                        transform: {
                          rotate: "",
                          scale: "",
                        },
                      },
                      name: "返回主页",
                      _config: "F7:解除关联|Cancel|blue|true",
                      HyperText: "backhome",
                      events: [],
                      created: "",
                      mounted: "",
                    },
                    {
                      id: "bottombutton_0285d80b",
                      type: "bottombutton",
                      style: {
                        position: "absolute",
                        width: "165",
                        height: "60",
                        top: 20,
                        left: "750",
                        right: "",
                        bottom: "",
                        backgroundImage: "",
                        backgroundColor: "",
                        backgroundRepeat: "no-repeat",
                        backgroundSize: "100% 100%",
                        color: "",
                        fontSize: "",
                        fontWeight: "",
                        transform: {
                          rotate: "",
                          scale: "",
                        },
                      },
                      name: "底部按钮",
                      _config: "F7:解除关联|Cancel|blue|true",
                      HyperText: "bottombutton",
                      events: [],
                      created: "",
                      mounted: "",
                    },
                    {
                      id: "bottombutton_b5eee126",
                      type: "bottombutton",
                      style: {
                        position: "absolute",
                        width: "165",
                        height: "60",
                        top: "20",
                        left: "1000",
                        right: "",
                        bottom: "",
                        backgroundImage: "",
                        backgroundColor: "",
                        backgroundRepeat: "no-repeat",
                        backgroundSize: "100% 100%",
                        color: "",
                        fontSize: "",
                        fontWeight: "",
                        transform: {
                          rotate: "",
                          scale: "",
                        },
                      },
                      name: "底部按钮",
                      _config: "F7:解除关联|Cancel|blue|true",
                      HyperText: "bottombutton",
                      events: [],
                      created: "",
                      mounted: "",
                    },
                  ],
                  events: [],
                  created: "",
                  mounted: "",
                },
              ],
              events: [],
              created: "",
              mounted: "",
            },
          ],
          events: [],
          created: "",
          mounted: "",
        },
        {
          id: "callmanager_cbabc8af",
          type: "callmanager",
          style: {
            position: "absolute",
            width: "330",
            height: "110",
            top: "180",
            left: -1,
            right: "",
            bottom: "",
            backgroundImage: "",
            backgroundColor: "",
            backgroundRepeat: "no-repeat",
            backgroundSize: "100% 100%",
            color: "",
            fontSize: "",
            fontWeight: "",
            transform: {
              rotate: "",
              scale: "",
            },
          },
          name: "呼叫",
          callHelpFlag: "1",
          HyperText: "callmanager",
          events: [],
          created: "",
          mounted: "",
        },
        {
          id: "pagetimer_4f9d03c0",
          type: "pagetimer",
          style: {
            position: "absolute",
            width: 111,
            height: 76,
            top: 230,
            left: 1168,
            right: "",
            bottom: "",
            backgroundImage: "",
            backgroundColor: "",
            backgroundRepeat: "no-repeat",
            backgroundSize: "100% 100%",
            color: "",
            fontSize: "",
            fontWeight: "",
            transform: {
              rotate: "",
              scale: "",
            },
          },
          name: "定时器",
          time: "50",
          isRemind: false,
          HyperText: "pagetimer",
          events: [],
          created: "",
          mounted: "",
        },
      ],
      mounted: "",
    },
    {
      id: "page_d1cd9859",
      type: "page",
      layout: "absolute",
      style: {
        width: "1280",
        height: "1024",
        position: "relative",
        top: 0,
        left: 0,
        right: "",
        bottom: "",
        backgroundImage: "https://127.0.0.1:9000/img/back_1600x1200.bac1a12c.jpg",
        backgroundColor: "",
        backgroundRepeat: "no-repeat",
        backgroundSize: "100% 100%",
        color: "",
        fontSize: "",
        fontWeight: "",
        transform: {
          rotate: "",
          scale: "",
        },
      },
      name: "系统初始化页面",
      items: [
        {
          id: "framecontent_60b375ea",
          type: "framecontent",
          style: {
            position: "absolute",
            width: "1230",
            height: 841,
            top: "130",
            left: "25",
            right: "",
            bottom: "",
            backgroundImage: "",
            backgroundColor: "",
            backgroundRepeat: "no-repeat",
            backgroundSize: "100% 100%",
            color: "",
            fontSize: "",
            fontWeight: "",
            transform: {
              rotate: "",
              scale: "",
            },
          },
          name: "容器",
          _appname: "",
          _title: "",
          HyperText: "frame-content",
          items: [
            {
              id: "progress_d1c5dae1",
              type: "progress",
              style: {
                position: "absolute",
                width: "225",
                height: "225",
                top: 340,
                left: 502.5,
                right: "",
                bottom: "",
                backgroundImage: "",
                backgroundColor: "",
                backgroundRepeat: "no-repeat",
                backgroundSize: "100% 100%",
                color: "",
                fontSize: "",
                fontWeight: "",
                transform: {
                  rotate: "",
                  scale: "",
                },
              },
              name: "进度条",
              progress: "50",
              isRemind: false,
              progressType: "circle",
              pgsStrokeWidth: "30",
              pgsWidth: "225",
              color: "rgb(6,132,94)",
              HyperText: "progress",
              events: [],
              created: "",
              mounted: "",
            },
            {
              id: "text_4e23f61b",
              type: "text",
              style: {
                width: "auto",
                height: "auto",
                lineHeight: "initial",
                position: "absolute",
                top: 251.4677326978342,
                left: 391,
                right: "",
                bottom: "",
                backgroundImage: "",
                backgroundColor: null,
                backgroundRepeat: "no-repeat",
                backgroundSize: "100% 100%",
                color: "rgba(33, 33, 33, 1)",
                fontSize: "36px",
                fontWeight: "500",
                transform: {
                  rotate: "",
                  scale: "",
                },
              },
              name: "文本",
              text: "系统正在初始化，请稍后......",
              multiple: true,
              events: [],
              created: "",
              mounted: "",
            },
          ],
          events: [],
          created: "",
          mounted: "",
        },
      ],
      title: "",
      events: [],
      created: "",
      mounted: "",
    },
    {
      id: "page_eb7b7ed5",
      type: "page",
      layout: "absolute",
      style: {
        width: "1280",
        height: "1024",
        position: "relative",
        top: "0",
        left: 0,
        right: "",
        bottom: "",
        backgroundImage: "https://127.0.0.1:9000/img/back_1600x1200.bac1a12c.jpg",
        backgroundColor: "",
        backgroundRepeat: "no-repeat",
        backgroundSize: "100% 100%",
        color: "",
        fontSize: "",
        fontWeight: "",
        transform: {
          rotate: "",
          scale: "",
        },
      },
      name: "插入银行卡页面",
      items: [
        {
          id: "callmanager_2b91dd20",
          type: "callmanager",
          style: {
            position: "absolute",
            width: 252,
            height: 97,
            top: 230,
            left: 0,
            right: "",
            bottom: "",
            backgroundImage: "",
            backgroundColor: "",
            backgroundRepeat: "no-repeat",
            backgroundSize: "100% 100%",
            color: "",
            fontSize: "",
            fontWeight: "",
            transform: {
              rotate: "",
              scale: "",
            },
          },
          name: "呼叫",
          callHelpFlag: "1",
          HyperText: "callmanager",
          events: [],
          created: "",
          mounted: "",
        },
        {
          id: "framecontent_c523d2ec",
          type: "framecontent",
          style: {
            position: "absolute",
            width: 1236,
            height: 858,
            top: 124,
            left: 22,
            right: "",
            bottom: "",
            backgroundImage: "",
            backgroundColor: "",
            backgroundRepeat: "no-repeat",
            backgroundSize: "100% 100%",
            color: "",
            fontSize: "",
            fontWeight: "",
            transform: {
              rotate: "",
              scale: "",
            },
          },
          name: "容器",
          _appname: "",
          _title: "",
          HyperText: "frame-content",
          items: [
            {
              id: "bgcontent_8a3beac1",
              type: "bgcontent",
              style: {
                position: "absolute",
                width: 379,
                height: 356,
                top: 302,
                left: 428.5,
                right: "",
                bottom: "",
                backgroundImage: "",
                backgroundColor: "",
                backgroundRepeat: "no-repeat",
                backgroundSize: "100% 100%",
                color: "",
                fontSize: "",
                fontWeight: "",
                transform: {
                  rotate: "",
                  scale: "",
                },
              },
              name: "图片背景",
              appName: "MainFramePage",
              pageName: "Pic_DeviceDealing",
              imgName: "InsertICCard.gif",
              HyperText: "bg-content",
              events: [],
              created: "",
              mounted: "",
            },
            {
              id: "pagetimer_c274fb97",
              type: "pagetimer",
              style: {
                position: "absolute",
                width: "100",
                height: "100",
                top: "100",
                left: "1100",
                right: "",
                bottom: "",
                backgroundImage: "",
                backgroundColor: "",
                backgroundRepeat: "no-repeat",
                backgroundSize: "100% 100%",
                color: "",
                fontSize: "",
                fontWeight: "",
                transform: {
                  rotate: "",
                  scale: "",
                },
              },
              name: "定时器",
              time: "10",
              isRemind: false,
              HyperText: "pagetimer",
              events: [],
              created: "",
              mounted: "",
            },
            {
              id: "text_d28f8147",
              type: "text",
              style: {
                width: "auto",
                height: "auto",
                lineHeight: "initial",
                position: "absolute",
                top: "200",
                left: 434,
                right: "",
                bottom: "",
                backgroundImage: "",
                backgroundColor: "",
                backgroundRepeat: "no-repeat",
                backgroundSize: "100% 100%",
                color: "rgba(33, 33, 33, 1)",
                fontSize: "2.875vw",
                fontWeight: "500",
                transform: {
                  rotate: "",
                  scale: "",
                },
              },
              name: "文本",
              text: "请插入您的银行卡",
              multiple: true,
              events: [],
              created: "",
              mounted: "",
            },
            {
              id: "backhome_bf424ee7",
              type: "backhome",
              style: {
                position: "absolute",
                width: "200",
                height: "60",
                top: "780",
                left: 48,
                right: "",
                bottom: "",
                backgroundImage: "",
                backgroundColor: "",
                backgroundRepeat: "no-repeat",
                backgroundSize: "100% 100%",
                color: "",
                fontSize: "",
                fontWeight: "",
                transform: {
                  rotate: "",
                  scale: "",
                },
              },
              name: "返回主页",
              _config: "F7:解除关联|Cancel|blue|true",
              HyperText: "backhome",
              events: [],
              created: "",
              mounted: "",
            },
            {
              id: "bottombutton_e89bc989",
              type: "bottombutton",
              style: {
                position: "absolute",
                width: "165",
                height: "60",
                top: "780",
                left: 1026,
                right: "",
                bottom: "",
                backgroundImage: "",
                backgroundColor: "",
                backgroundRepeat: "no-repeat",
                backgroundSize: "100% 100%",
                color: "",
                fontSize: "",
                fontWeight: "",
                transform: {
                  rotate: "",
                  scale: "",
                },
              },
              name: "底部按钮",
              _config: "F7:上一步|Cancel|blue|true",
              HyperText: "bottombutton",
              events: [],
              created: "",
              mounted: "",
            },
          ],
          events: [],
          created: "",
          mounted: "",
        },
      ],
      title: "",
      events: [],
      created: "",
      mounted: "",
    },
    {
      id: "page_b1ad7683",
      type: "page",
      layout: "absolute",
      style: {
        width: "1280",
        height: "1024",
        position: "relative",
        top: 0,
        left: 0,
        right: "",
        bottom: "",
        backgroundImage: "",
        backgroundColor: "",
        backgroundRepeat: "no-repeat",
        backgroundSize: "100% 100%",
        color: "",
        fontSize: "",
        fontWeight: "",
        transform: {
          rotate: "",
          scale: "",
        },
      },
      name: "个人业务输入银行卡密码",
      items: [
        {
          id: "callmanager_a01deb46",
          type: "callmanager",
          style: {
            position: "absolute",
            width: "330",
            height: "110",
            top: 195.62120407420448,
            left: "0",
            right: "",
            bottom: "",
            backgroundImage: "",
            backgroundColor: "",
            backgroundRepeat: "no-repeat",
            backgroundSize: "100% 100%",
            color: "",
            fontSize: "",
            fontWeight: "",
            transform: {
              rotate: "",
              scale: "",
            },
          },
          name: "呼叫",
          callHelpFlag: "1",
          HyperText: "callmanager",
          events: [],
          created: "",
          mounted: "",
        },
        {
          id: "pagetimer_0bf85426",
          type: "pagetimer",
          style: {
            position: "absolute",
            width: "100",
            height: "100",
            top: 186.04751345301082,
            left: "",
            right: "50",
            bottom: "",
            backgroundImage: "",
            backgroundColor: "",
            backgroundRepeat: "no-repeat",
            backgroundSize: "100% 100%",
            color: "",
            fontSize: "",
            fontWeight: "",
            transform: {
              rotate: "",
              scale: "",
            },
          },
          name: "定时器",
          time: "10",
          isRemind: false,
          HyperText: "pagetimer",
          events: [],
          created: "",
          mounted: "",
        },
        {
          id: "framecontent_444aacba",
          type: "framecontent",
          style: {
            position: "absolute",
            width: 1228,
            height: 888,
            top: 101,
            left: 26,
          },
          name: "容器",
          _appname: "应用",
          _title: "标题",
          HyperText: "frame-content",
          items: [
            {
              id: "container_0ffa6463",
              type: "container",
              layout: "absolute",
              style: {
                width: "828",
                height: "18vh",
                position: "absolute",
                top: 135,
                left: 200,
                right: "",
                bottom: "",
                backgroundImage: "",
                backgroundColor: "rgba(255, 241, 238, 1)",
                backgroundRepeat: "no-repeat",
                backgroundSize: "100% 100%",
                color: "",
                fontSize: "",
                fontWeight: "",
                transform: {
                  rotate: "",
                  scale: "",
                },
              },
              name: "组",
              items: [
                {
                  id: "text_8f19bb11",
                  type: "text",
                  style: {
                    width: "auto",
                    height: "auto",
                    lineHeight: "initial",
                    position: "absolute",
                    top: 19,
                    left: 349,
                    right: "",
                    bottom: "",
                    backgroundImage: "",
                    backgroundColor: "",
                    backgroundRepeat: "no-repeat",
                    backgroundSize: "100% 100%",
                    color: "rgba(206, 135, 146, 1)",
                    fontSize: "2vw",
                    fontWeight: "400",
                    transform: {
                      rotate: "",
                      scale: "",
                    },
                  },
                  name: "文本",
                  text: "安全提示",
                  multiple: true,
                  events: [],
                  created: "",
                  mounted: "",
                },
                {
                  id: "text_be08dc26",
                  type: "text",
                  style: {
                    width: 776,
                    height: 111,
                    lineHeight: "initial",
                    position: "absolute",
                    top: 75,
                    left: 27,
                    right: "",
                    bottom: "",
                    backgroundImage: "",
                    backgroundColor: null,
                    backgroundRepeat: "no-repeat",
                    backgroundSize: "100% 100%",
                    color: "rgba(206, 135, 146, 1)",
                    fontSize: "1.625vw",
                    fontWeight: "400",
                    transform: {
                      rotate: "",
                      scale: "",
                    },
                  },
                  name: "文本",
                  text: "请保护好您的密码，当您做交易时，请确认身边没有其他人。操作完毕请别忘记取回您的卡！为了您的资金安全，请不要将您的卡号或密码告诉他人。",
                  multiple: true,
                  events: [],
                  created: "",
                  mounted: "",
                },
              ],
              events: [],
              created: "",
              mounted: "",
            },
            {
              id: "container_b9cac53e",
              type: "container",
              layout: "absolute",
              style: {
                width: 575,
                height: 422,
                position: "absolute",
                top: 360,
                left: 550,
              },
              name: "组",
              items: [
                {
                  id: "text_0691ecb1",
                  type: "text",
                  style: {
                    width: "70",
                    height: "70",
                    lineHeight: "initial",
                    position: "absolute",
                    top: 110,
                    left: "50",
                    right: "",
                    bottom: "",
                    backgroundImage: "",
                    backgroundColor: "rgba(255, 255, 255, 1)",
                    backgroundRepeat: "no-repeat",
                    backgroundSize: "100% 100%",
                    color: "",
                    fontSize: "100",
                    fontWeight: "",
                    transform: {
                      rotate: "",
                      scale: "",
                    },
                  },
                  name: "文本",
                  text: "",
                  multiple: true,
                  events: [],
                  created: "",
                  mounted: "",
                },
                {
                  id: "text_8c26a45e",
                  type: "text",
                  style: {
                    width: "70",
                    height: "70",
                    lineHeight: "initial",
                    position: "absolute",
                    top: "110",
                    left: "290",
                    right: "",
                    bottom: "",
                    backgroundImage: "",
                    backgroundColor: "rgba(255, 255, 255, 1)",
                    backgroundRepeat: "no-repeat",
                    backgroundSize: "100% 100%",
                    color: "",
                    fontSize: "100",
                    fontWeight: "",
                    transform: {
                      rotate: "",
                      scale: "",
                    },
                  },
                  name: "文本",
                  text: "",
                  multiple: true,
                  events: [],
                  created: "",
                  mounted: "",
                },
                {
                  id: "text_97164fa0",
                  type: "text",
                  style: {
                    width: "70",
                    height: "70",
                    lineHeight: "initial",
                    position: "absolute",
                    top: "110",
                    left: "450",
                    right: "",
                    bottom: "",
                    backgroundImage: "",
                    backgroundColor: "rgba(255, 255, 255, 1)",
                    backgroundRepeat: "no-repeat",
                    backgroundSize: "100% 100%",
                    color: "",
                    fontSize: "100",
                    fontWeight: "",
                    transform: {
                      rotate: "",
                      scale: "",
                    },
                  },
                  name: "文本",
                  text: "",
                  multiple: true,
                  events: [],
                  created: "",
                  mounted: "",
                },
                {
                  id: "text_0874dc4b",
                  type: "text",
                  style: {
                    width: "70",
                    height: "70",
                    lineHeight: "initial",
                    position: "absolute",
                    top: 110,
                    left: "370",
                    right: "",
                    bottom: "",
                    backgroundImage: "",
                    backgroundColor: "rgba(255, 255, 255, 1)",
                    backgroundRepeat: "no-repeat",
                    backgroundSize: "100% 100%",
                    color: "",
                    fontSize: "100",
                    fontWeight: "",
                    transform: {
                      rotate: "",
                      scale: "",
                    },
                  },
                  name: "文本",
                  text: "",
                  multiple: true,
                  events: [],
                  created: "",
                  mounted: "",
                },
                {
                  id: "text_ba513dc9",
                  type: "text",
                  style: {
                    width: "70",
                    height: "70",
                    lineHeight: "initial",
                    position: "absolute",
                    top: 110,
                    left: "210",
                    right: "",
                    bottom: "",
                    backgroundImage: "",
                    backgroundColor: "rgba(255, 255, 255, 1)",
                    backgroundRepeat: "no-repeat",
                    backgroundSize: "100% 100%",
                    color: "",
                    fontSize: "100",
                    fontWeight: "",
                    transform: {
                      rotate: "",
                      scale: "",
                    },
                  },
                  name: "文本",
                  text: "",
                  multiple: true,
                  events: [],
                  created: "",
                  mounted: "",
                },
                {
                  id: "text_372a3c08",
                  type: "text",
                  style: {
                    width: "70",
                    height: "70",
                    lineHeight: "initial",
                    position: "absolute",
                    top: 110,
                    left: "130",
                    right: "",
                    bottom: "",
                    backgroundImage: "",
                    backgroundColor: "rgba(255, 255, 255, 1)",
                    backgroundRepeat: "no-repeat",
                    backgroundSize: "100% 100%",
                    color: "",
                    fontSize: "100",
                    fontWeight: "",
                    transform: {
                      rotate: "",
                      scale: "",
                    },
                  },
                  name: "文本",
                  text: "",
                  multiple: true,
                  events: [],
                  created: "",
                  mounted: "",
                },
                {
                  id: "text_bfad4fa3",
                  type: "text",
                  style: {
                    width: "auto",
                    height: "auto",
                    lineHeight: "initial",
                    position: "absolute",
                    top: "20",
                    left: 117,
                    right: "",
                    bottom: "",
                    backgroundImage: "",
                    backgroundColor: "",
                    backgroundRepeat: "no-repeat",
                    backgroundSize: "100% 100%",
                    color: "",
                    fontSize: "2.25vw",
                    fontWeight: "500",
                    transform: {
                      rotate: "",
                      scale: "",
                    },
                  },
                  name: "文本",
                  text: "输入您的6位数交易密码",
                  multiple: true,
                  events: [],
                  created: "",
                  mounted: "",
                },
                {
                  id: "ul_43b08657",
                  type: "ul",
                  style: {
                    width: 407,
                    height: 122,
                    position: "absolute",
                    top: 247,
                    left: 70,
                    right: "",
                    bottom: "",
                    backgroundImage: "",
                    backgroundColor: "",
                    backgroundRepeat: "no-repeat",
                    backgroundSize: "100% 100%",
                    color: "rgba(113, 113, 113, 1)",
                    fontSize: "1.625vw",
                    fontWeight: "400",
                    transform: {
                      rotate: "",
                      scale: "",
                    },
                  },
                  name: "ul",
                  multiple: true,
                  items: [
                    {
                      id: "li_6e4db01b",
                      type: "li",
                      style: {
                        width: "auto",
                        height: "auto",
                        position: "absolute",
                        top: 0,
                        left: "0",
                        right: "",
                        bottom: "",
                        backgroundImage: "",
                        backgroundColor: "",
                        backgroundRepeat: "no-repeat",
                        backgroundSize: "100% 100%",
                        color: "",
                        fontSize: "",
                        fontWeight: "",
                        transform: {
                          rotate: "",
                          scale: "",
                        },
                      },
                      name: "li",
                      text: "请勿向任何人透露您的密码",
                      multiple: true,
                      items: [],
                      HyperText: "li",
                      events: [],
                      created: "",
                      mounted: "",
                    },
                    {
                      id: "li_d8783c0e",
                      type: "li",
                      style: {
                        width: "auto",
                        height: "auto",
                        position: "absolute",
                        top: "80",
                        left: "0",
                        right: "",
                        bottom: "",
                        backgroundImage: "",
                        backgroundColor: "",
                        backgroundRepeat: "no-repeat",
                        backgroundSize: "100% 100%",
                        color: "",
                        fontSize: "",
                        fontWeight: "",
                        transform: {
                          rotate: "",
                          scale: "",
                        },
                      },
                      name: "li",
                      text: "输入您的6位数交易密码",
                      multiple: true,
                      items: [],
                      HyperText: "li",
                      events: [],
                      created: "",
                      mounted: "",
                    },
                    {
                      id: "li_5fc31455",
                      type: "li",
                      style: {
                        width: "auto",
                        height: "auto",
                        position: "absolute",
                        top: "40",
                        left: "0",
                        right: "",
                        bottom: "",
                        backgroundImage: "",
                        backgroundColor: "",
                        backgroundRepeat: "no-repeat",
                        backgroundSize: "100% 100%",
                        color: "",
                        fontSize: "",
                        fontWeight: "",
                        transform: {
                          rotate: "",
                          scale: "",
                        },
                      },
                      name: "li",
                      text: "请勿在有人窥视和干扰时操作",
                      multiple: true,
                      items: [],
                      HyperText: "li",
                      events: [],
                      created: "",
                      mounted: "",
                    },
                  ],
                  HyperText: "ul",
                  text: "",
                  events: [],
                  created: "",
                  mounted: "",
                },
              ],
            },
            {
              id: "bgcontent_8d7738dd",
              type: "bgcontent",
              style: {
                position: "absolute",
                width: "31.7vh",
                height: "31.7vh",
                top: 360,
                left: 200,
                right: "",
                bottom: "",
                backgroundImage: "",
                backgroundColor: "",
                backgroundRepeat: "no-repeat",
                backgroundSize: "100% 100%",
                color: "",
                fontSize: "",
                fontWeight: "",
                transform: {
                  rotate: "",
                  scale: "",
                },
              },
              name: "图片背景",
              appName: "MainFramePage",
              pageName: "InputPersonalPIN",
              imgName: "inputPin.png",
              HyperText: "bg-content",
              events: [],
              created: "",
              mounted: "",
            },
          ],
        },
        {
          id: "backhome_dbe71bcb",
          type: "backhome",
          style: {
            position: "absolute",
            width: "12.5vw",
            height: "4.063vw",
            top: "910",
            left: 49,
            right: "",
            bottom: "",
            backgroundImage: "",
            backgroundColor: "",
            backgroundRepeat: "no-repeat",
            backgroundSize: "100% 100%",
            color: "",
            fontSize: "",
            fontWeight: "",
            transform: {
              rotate: "",
              scale: "",
            },
          },
          name: "返回主页",
          _config: "F7:解除关联|Cancel|blue|true",
          HyperText: "backhome",
          events: [],
          created: "",
          mounted: "",
        },
        {
          id: "bottombutton_91e0774e",
          type: "bottombutton",
          style: {
            position: "absolute",
            width: "12.5vw",
            height: "4.063vw",
            top: "910",
            left: "1050",
            right: "",
            bottom: "",
            backgroundImage: "",
            backgroundColor: "",
            backgroundRepeat: "no-repeat",
            backgroundSize: "100% 100%",
            color: "",
            fontSize: "",
            fontWeight: "",
            transform: {
              rotate: "",
              scale: "",
            },
          },
          name: "底部按钮",
          _config: "F7:解除关联|Cancel|blue|true",
          HyperText: "bottombutton",
          events: [],
          created: "",
          mounted: "",
        },
      ],
      title: "",
      events: [],
      created: "",
      mounted: "",
    },
  ],
};
